language: c

sudo: required

matrix:
    include:
        - os: linux
          dist: trusty
        - os: osx
          osx_image: xcode7.3
        - os: osx
          osx_image: xcode7.1
        - os: osx
          osx_image: beta-xcode6.2

before_install:
    - if [ `uname` = "Linux" ]; then
          sudo apt-get update -qq;
          sudo apt-get install -y build-essential debhelper librtlsdr-dev libusb-1.0-0-dev pkg-config fakeroot libbladerf-dev dh-systemd;
      elif [ `uname` = "Darwin" ]; then
          brew update;
          brew install -v librtlsdr;
      fi

script:
    - if [ `uname` = "Linux" ]; then
          dpkg-buildpackage -b -us -uc;
      elif [ `uname` = "Darwin" ]; then
          make;
         make test;
      fi
